apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cloudtrace-agent
  namespace: acm-workshop-425-gke
  annotations:
    config.kubernetes.io/depends-on: iam.cnrm.cloud.google.com/namespaces/acm-workshop-425-gke/IAMServiceAccount/gke-primary-pool
spec:
  memberFrom:
    serviceAccountRef:
      name: gke-primary-pool
      namespace: acm-workshop-425-gke
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: acm-workshop-425-gke
  role: roles/cloudtrace.agent
