apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gke-acm-membership
  namespace: acm-workshop-425-gke
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/acm-workshop-425-gke/GKEHubMembership/gke,gkehub.cnrm.cloud.google.com/namespaces/acm-workshop-425-gke/GKEHubFeature/configmanagement
spec:
  projectRef:
    external: acm-workshop-425-gke
  location: global
  membershipRef:
    name: gke
  featureRef:
    name: configmanagement
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        policyDir: config-sync
        secretType: none
        syncBranch: main
        syncRepo: https://github.com/rick-c-goog/acm-workshop-gke-configs-repo
    policyController:
      enabled: true
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: false
    version: "1.11.0"
