apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: gke
  namespace: acm-workshop-425-gke
  annotations:
    config.kubernetes.io/depends-on: compute.cnrm.cloud.google.com/namespaces/acm-workshop-425-gke/ComputeNetwork/gke
spec:
  ipCidrRange: 10.2.0.0/20
  region: us-east4
  networkRef:
    name: gke
  secondaryIpRange:
  - rangeName: servicesrange
    ipCidrRange: 10.3.0.0/20
  - rangeName: clusterrange
    ipCidrRange: 10.4.0.0/20
